### PR TITLE
Allow for search toolbars to have the search hidden (for checklists)

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**

### CODE REVIEW

**Comment by Blackbaud-AlexKingman** [comment]
Pulling this into `list-builder-view-checklist` seems to do the trick. One question though: the default checklist view (with the search bar enabled) has a 1px border on top. As soon as the toolbar is removed, its no longer there. Is that a problem?

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ToddRoberts thoughts on @Blackbaud-AlexKingman's question?

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled](https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled)

**Comment by Blackbaud-AlexKingman** [comment]
Example showing top border missing. Is this OK?

Screen Shot 2020-01-28 at 11 46 28 AM

**Comment by Blackbaud-ToddRoberts** [comment]
Top border needs to be there

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled](https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled](https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled](https://host.nxt.blackbaud.com/skyux-list-builder?_sp.spa=pr-search-toolbar-search-not-enabled)

**Comment by Blackbaud-AlexKingman** [comment]
Now I'm seeing a blank toolbar. Is this expected?

Screen Shot 2020-03-11 at 2 08 21 PM

My template code:
```
<div id="screenshot-list-view-checklist" style="background-color: white">
  <sky-list [data]="data">
    <sky-list-toolbar
      [searchEnabled]="false"
    >
    </sky-list-toolbar>
    <sky-list-view-checklist
      label="column1"
      description="column2"
      name="checklist"
      [selectMode]="selectMode"
    >
    </sky-list-view-checklist>
  </sky-list>
</div>
```

**Pull request merged**
